config/routes.rb
#Made by Augustinas Cerniauskas, edit by Augustinas Cerniauskas and Tautvydas Cerniauskas
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  get 'sessions/new'

  get 'users/new'

  #get '/regions', to: 'static_pages#regions'
  
  get '/types', to: 'static_pages#types'

  get '/contact', to: 'static_pages#contact'

  get '/about', to: 'static_pages#about'
  
  get  '/signup',  to: 'users#new'
  
  post '/signup',  to: 'users#create'
  
  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'
  
  resources :places, except: [:update, :edit, :destroy]
  
  get '/regions', to: 'places#index'
  
  resources :users

  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
#Made by Tautvydas Cerniauskas
class Place < ApplicationRecord
  attr_accessor :raw_address

  geocoded_by :raw_address
  reverse_geocoded_by :latitude, :longitude

  after_validation -> {
    self.address = self.raw_address
    geocode
  }, if: ->(obj){ obj.raw_address.present? and obj.raw_address != obj.address }

  after_validation :reverse_geocode, unless: ->(obj) { obj.raw_address.present? },
                   if: ->(obj){ obj.latitude.present? and obj.latitude_changed? and obj.longitude.present? and obj.longitude_changed? }
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/places_controller.rb
#Made by Tautvydas Cerniauskas
class PlacesController < ApplicationController
  
  
  def index
    @places = Place.order('created_at DESC')
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
    end
  end

  def show
    @place = Place.find(params[:id])
    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Place added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def place_params
    params.require(:place).permit(:title, :raw_address, :latitude, :longitude, :visited_by)
  end
end

app/controllers/sessions_controller.rb
#Made by Augustinas Cerniauskas
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def regions
  end

  def types
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
#Made by Augustinas Cerniauskas, edit by Augustinas Cerniauskas and Tautvydas Cerniauskas
class UsersController < ApplicationController
  def show
      @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the One Pound Coffee App!"
      redirect_to @user
      # Handle a successful save.
    else
      render 'new'
    end
  end
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
#Made by Tautvydas Cerniauskas
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
#Made by Augustinas Cerniauskas
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<!--Made by Augustinas Cerniauskas -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<footer class="footer">
<!--  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
        <li><%= link_to "Home",       root_path %></li>
        <li><%= link_to "Regions",    regions_path %></li>
        <li><%= link_to "Types",      types_path %></li>
        <li><%= link_to "About",      about_path %></li>
        <li><%= link_to "Contact",    contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>-->
  
	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Join us on social media!</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
</footer>

app/views/layouts/_header.html.erb
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>



<!--Made by Augustinas Cerniauskas -->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "world coffee", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",       root_path %></li>
        <li><%= link_to "Regions",    regions_path %></li>
        <li><%= link_to "Types",      types_path %></li>
        <li><%= link_to "About",      about_path %></li>
        <li><%= link_to "Contact",    contact_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Admin", '/admin' %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!--Made by Augustinas Cerniauskas -->
<!DOCTYPE html>
<html>
  <head>
    
        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/places/_form.html.erb
<!--Made by Tautvydas Cerniauskas -->
<%= form_for @place do |f| %>
  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :visited_by %>
    <%= f.text_field :visited_by, class: "form-control" %>
  </fieldset>

  <h4>Enter either address or coordinates</h4>
  <fieldset class="form-group">
    <%= f.label :raw_address, 'Address' %>
    <%= f.text_field :raw_address, class: "form-control" %>
    <small class="text-muted">You can also enter IP. Your IP is <%= request.ip %></small>
  </fieldset>

  <div class="form-group row">
    <div class="col-sm-1">
      <%= f.label :latitude %>
    </div>

    <div class="col-sm-3">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>

    <div class="col-sm-1">
      <%= f.label :longitude %>
    </div>

    <div class="col-sm-3">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>

    <div class="col-sm-4">
      <a href="#" id="find-on-map" class="btn btn-info btn-sm">Find on the map</a>
    </div>
  </div>

  <%= f.submit 'Add!', class: 'btn btn-primary' %>
<% end %>

<div class="card">
  <div class="card-block">
    <div id="map"></div>
  </div>
</div>

app/views/places/_place.html.erb
<!--Made by Tautvydas Cerniauskas -->
<li>
  <%= link_to place.title, place_path(place) %>
</li>

app/views/places/index.html.erb
<!--Made by Tautvydas Cerniauskas -->
<script src="//maps.google.com/maps/api/js?key=AIzaSyDVZp_Ur2RNJJ4MfzpBMVE7p80uqo18AgU"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<header><h1 class="display-4">Places</h1></header>

<%= link_to 'Add place', new_place_path, class: 'btn btn-primary btn-lg' %>

<div class="card">
  <div class="card-block">
    <ul>
      <%= render @places %>
    </ul>
  </div>
</div>

app/views/places/new.html.erb
<!--Made by Tautvydas Cerniauskas -->
<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form' %>

app/views/places/show.html.erb
<!--Made by Tautvydas Cerniauskas -->
<script src="//maps.google.com/maps/api/js?key=AIzaSyDVZp_Ur2RNJJ4MfzpBMVE7p80uqo18AgU"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<header><h1 class="display-4"><%= @place.title %></h1></header>

<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

<%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@place.latitude},#{@place.longitude}&markers=#{@place.latitude},#{@place.longitude}&zoom=7&size=640x400&key=AIzaSyDVZp_Ur2RNJJ4MfzpBMVE7p80uqo18AgU",
              class: 'img-fluid img-rounded', alt: "#{@place.title} on the map"%>


<%= link_to 'Go Back', regions_path, class: 'btn btn-primary btn-lg' %>

app/views/shared/_error_messages.html.erb
<!--Made by Augustinas Cerniauskas -->
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<!--Made by Augustinas Cerniauskas -->
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | One Pound Coffee</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
     About World Coffee
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<!--Made by Augustinas Cerniauskas -->
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | One Pound Coffee</title>
  </head>
  <body>
    <h1>Contact</h1>
    <p>
      Contact details
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!--Made by Augustinas Cerniauskas -->
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <head>
    <title><%= yield(:title) %> | One Pound Coffee</title>
  </head>
  <h1>Welcome to the World Coffee page!</h1>



</div>

    <div class="container">

        <!-- Marketing Icons Section -->
        <div class="row">
            <div class="col-lg-12">
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i> Join us!</h4>
                    </div>
                    <div class="panel-body">
                        <p>Easy and fast sign up application!</p>
                        <a  <%= link_to "Sign up now!", signup_path, class: "btn btn-default" %></a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i> Learn More About Coffee </h4>
                    </div>
                    <div class="panel-body">
                        <p>DIfferent types of coffee and raosting techniques</p>
                        <a  <%= link_to "Learn more!", types_path, class: "btn btn-default" %></a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-compass"></i> Find the largest coffee producing coutries!</h4>
                    </div>
                    <div class="panel-body">
                        <p>Top exporting coutries in the world!</p>
                        <a  <%= link_to "Search now!", regions_path, class: "btn btn-default" %></a>
                    </div>
                </div>
            </div>
        </div>

app/views/static_pages/regions.html.erb
<!--Made by Tautvydas Cerniauskas -->
<% provide(:title, "Regions") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | One Pound Coffee</title>
  </head>
  <body>
    <h1>Regions</h1>
    <p>
      Different regions of coffee from different farmers.
    </p>
  </body>
</html>

app/views/users/new.html.erb
<!--Made by Augustinas Cerniauskas -->
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--Made by Augustinas Cerniauskas -->
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>